Реализация ТЗ 10
Avseenkov/java-filmorate pull request #2
Opened 2022-10-26 09:11 UTC by Avseenkov

2022-10-27 07:29 UTC, LexLippi requested changes
Привет!

Хорошая работа, остались некоторые замечания. Написал их в ревью.

Желаю удачи!!!

2022-10-27 07:29 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmService filmService) {
Можно использовать аннотацию `@Autowired`

2022-10-27 07:29 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public UserController(UserService userService) {
Аналдогично про `Autowired`

2022-10-27 07:29 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        return new HashSet<>(likes);
Какой смысл ещё раз в `HashSet` оборачивать? Почему просто `return likes;` не подходит?

2022-10-27 07:29 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +        return new HashSet<>(friends);
Аналогично, непонятно зачем оборачивать в `HashSet`

2022-10-27 07:29 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    public Film delete(Film film) {
Зачем тебе для удаления целиком сущность фильм?
Кажется, что ты используешь только идентификатор. Так зачем тогда просить от пользователя нашего API лишнюю информацию?

2022-10-27 07:29 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User delete(@RequestBody User user) {
В идеале, `HTTP`-метод `DELETE` почти всегда используется, как метод без тела (`request body`). Этого нет в спецификации этого метода, но многие компании, считают, что это bad practice.

https://stackoverflow.com/questions/299628/is-an-entity-body-allowed-for-an-http-delete-request

2022-10-27 07:29 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film delete(@RequestBody Film film) {
Про удаление написал в `UserController`

2022-10-27 07:29 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    public User delete(User user) {
Написал выше соображения по поводу аналогичного метода

2022-10-27 07:29 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +    User add(User user);
Надо либо в названии всех методов использовать название сущности, либо везде не использовать. Не стоит мешать подходы

2022-10-27 07:29 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +    Collection<User> allUsers();
По мне названию не хватает глагола

2022-10-27 07:29 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    Film getFilm(Integer id);
Либо везде писать суффикс `Film`, либо везде не писать

2022-10-27 07:29 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public UserService(UserStorage userStorage) {
Можно использовать `@Autowired`

2022-10-27 07:29 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        User user = userStorage.getUser(userId);
Кажется, что тут эта проверка лишняя. Если пользователя сейчас нет, то его лайк все равно стоит удалить, если он почему-то остался

2022-10-27 07:29 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return filmStorage.findAll().stream().sorted(Comparator.comparingInt(o -> -o.getLikes().size())).limit(count).collect(Collectors.toList());
Зависит от версии JDK, но если она позволяет, то лучше использовать `.toList()` вместо `.collect(Collectors.toList())`

2022-10-27 07:29 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return userStorage.delete(user);
При удалении пользователя стоит удалять все его лайки.
Либо так как этого метода нет в ТЗ, можно убрать метод удаления пользователя

2022-10-27 07:29 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +@AllArgsConstructor
Почему больше нигде не пользовался этой аннотацией? 
Либо везде её надо добавить, либо везде отказаться

2022-11-06 18:50 UTC, Avseenkov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        User user = userStorage.getUser(userId);
Если пользователь не найден нужно выдавать 404 по ТЗ

2022-11-06 18:52 UTC, Avseenkov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        return new HashSet<>(likes);
Если я верну return likes то смогу изменить коллекцию из вне

2022-11-07 08:37 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        return new HashSet<>(likes);
Тогда лучше использовать unmodifiable set для возврата наружу. Я понимаю, что если поправить что-то в этом set, то для внутреннего представления ничего не изменится.

**НО**:
1. Решение с unmodifiable set правильнее с точки зрения целей использования
2. Мы запрещаем вообще тем, кто может работать с нашим кодом добавлять в это множество. Это заставит других разработчиков задуматься о том, как для их целей правильнее использовать эту коллекцию
3. Есть небольшие плюсы с точки зрения перфоманса

https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/util/Set.html#unmodifiable

2022-11-07 08:42 UTC, LexLippi reviewed
Привет!

В целом, я со всеми исправлениями и ответами на мои комментарии согласен.
Если есть желание, то можно переделать на unmodifiable set, как я написал. Если нет, то перезашли работу в таком же состоянии и я её приму.

2022-11-08 18:52 UTC, LexLippi approved these changes
Привет!

Отличная работа, желаю удачи в следующих спринтах!!!

2022-11-09 09:59 UTC, merged